### ISSUE TITLE
Investigate rare panic

### ISSUE THREAD

**Issue by javorszky** [javorszky/go-generate-salts#2]
```
echo: http: panic serving 127.0.0.1:62364: runtime error: index out of range
goroutine 55033 [running]:
net/http.(*conn).serve.func1(0xc42026a140)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1726 +0xd0
panic(0x12afb00, 0x149c0e0)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
math/rand.(*rngSource).Uint64(...)
	/usr/local/Cellar/go/1.10/libexec/src/math/rand/rng.go:246
math/rand.(*rngSource).Int63(0xc42008ca00, 0x2b4ea4d200000000)
	/usr/local/Cellar/go/1.10/libexec/src/math/rand/rng.go:231 +0x8a
main.RandStringBytesMaskImprSrc(0x200, 0xc42051aaa0, 0x1012eac)
	/Users/javorszky/go/src/heroku-dotenv/salt.go:199 +0x10c
main.GenerateSaltsWP512(0xc420104460, 0xc42046c0f0)
	/Users/javorszky/go/src/heroku-dotenv/salt.go:77 +0x5d
main.GiveSalts(0x1347020, 0xc420226230, 0x0, 0xc420136000)
	/Users/javorszky/go/src/heroku-dotenv/salt.go:50 +0x22
heroku-dotenv/vendor/github.com/labstack/echo.(*Echo).Add.func1(0x1347020, 0xc420226230, 0x3, 0xc42046c0f4)
	/Users/javorszky/go/src/heroku-dotenv/vendor/github.com/labstack/echo/echo.go:478 +0x87
heroku-dotenv/vendor/github.com/labstack/echo.(*Echo).ServeHTTP.func1(0x1347020, 0xc420226230, 0xc42007e6d8, 0x1304580)
	/Users/javorszky/go/src/heroku-dotenv/vendor/github.com/labstack/echo/echo.go:575 +0x108
heroku-dotenv/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc42007e680, 0x1344d00, 0xc4202561c0, 0xc420422100)
	/Users/javorszky/go/src/heroku-dotenv/vendor/github.com/labstack/echo/echo.go:584 +0x259
net/http.serverHandler.ServeHTTP(0xc42007d040, 0x1344d00, 0xc4202561c0, 0xc420422100)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc42026a140, 0x1344f00, 0xc4204be0c0)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2795 +0x27b
```

This is at https://github.com/javorszky/go-generate-salts/commit/b611f5f363fb38f269d75f88aea355351f85c55c

Seems to be coming from `math.rand`

**Comment by javorszky** [comment]
This was caused by using a source that wasn't concurrency safe. Fixed with https://github.com/javorszky/go-generate-salts/commit/7b72dfd622c3e49808f540c5b0f06be37f11f789
